services:
  app:
    build: .
    image: stein-app:latest
    ports:
      - "8080:80"
      #- "443:443" # Force FrankenPHP to listen HTTP on port 80
      #- "443:443/udp" # Force FrankenPHP to listen HTTP on port 80
    volumes:
      - .:/app
    environment:
      SERVER_NAME: :80 # Force FrankenPHP to listen HTTP on port 80
      FRANKENPHP_CONFIG: worker ./public/worker.php
      # Application specific environment variables
      # If you have a .env file, those lines will be overridden by the variables defined in the .env file
      APP_NAME: app
      APP_VERSION: 1.0.0
      APP_ENV: production
      LOG_LEVEL: Warning
      TIMEZONE: Europe/Paris
      FRANKENPHP_NB_REQUEST_TO_RESTART: 1000
    tty: true
